{% set name = "kma" %}
{% set version = "1.3.20" %}
{% set sha256 = "6eaef5d15f7b1445f88d8249d58dc9a1e2b866915f548096e1731bffeb12059e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/genomicepidemiology/{{ name }}/get/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib
  
test:
  commands:
   - kma --help 2>&1|grep KMA >/dev/null
   - kma index  --help  2>&1 |grep kma_index
   - kma shm --help 2>&1 |grep kma_shm >/dev/null
   - kma update --help 2>&1 |grep KMA_update >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/kma
  summary: 'KMA is mapping a method designed to map raw reads directly against redundant databases, in an ultra-fast manner using seed and extend.'
  license: Apache-2.0
extra:
  identifiers:
    - doi:10.1186/s12859-018-2336-6
